companies = ['Google', 'Amazon', 'Microsoft', 'Facebook', 'Linkedin', 'Apple', 'Twitter']
visa_years = [i for i in range(2016, 2019)]

glassdoor = {
    'Google': 'https://www.glassdoor.com/Overview/Working-at-Google-EI_IE9079.11,17.htm',
    'Microsoft': 'https://www.glassdoor.com/Overview/Working-at-Microsoft-EI_IE1651.11,20.htm',
    'Amazon': "https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm",
    'Facebook': "https://www.glassdoor.com/facebook",
    'Linkedin': "https://www.glassdoor.com/Overview/Working-at-LinkedIn-EI_IE34865.11,19.htm",
    'Apple': "https://www.glassdoor.com/Overview/Working-at-Apple-EI_IE1138.11,16.htm",
    'Twitter': "https://www.glassdoor.com/Overview/Working-at-Twitter-EI_IE100569.11,18.htm",
    'Uber': "https://www.glassdoor.com/Overview/Working-at-Uber-EI_IE575263.11,15.htm",
    'Airbnb': "https://www.glassdoor.com/Overview/Working-at-Airbnb-EI_IE391850.11,17.htm",
    'Snapchat': "https://www.glassdoor.com/Overview/Working-at-Snap-EI_IE671946.11,15.htm",
    'Lyft': ['https://www.glassdoor.com/Overview/Working-at-Lyft-EI_IE700614.11,15.htm',
             'https://www.glassdoor.com/Salary/Lyft-Salaries-E700614.htm']
}

salaries = {
    'Data Scientist': 'https://www.glassdoor.com/Salaries/data-scientist-salary-SRCH_KO0,14.htm',
    'Software Engineer': 'https://www.glassdoor.com/Salaries/software-engineer-salary-SRCH_KO0,17.htm',
    'Data Engineer': 'https://www.glassdoor.com/Salaries/data-engineer-salary-SRCH_KO0,13.htm',
    'data analytics': 'https://www.glassdoor.com/Salaries/data-analytics-salary-SRCH_KO0,14.htm'
}

us_states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}